### ISSUE TITLE
Not compatible with ie11，an error is reported

### ISSUE THREAD

**Issue by leetia316** [b-zurg/react-collapse-pane#48]
I'm happy to find this library， but it doesn't seem to be compatible with ie11，The error is as follows:
<img width="1767" alt="error-img1" src="https://user-images.githubusercontent.com/12868906/113853408-3306af80-97d0-11eb-9ed2-d612a3a3269a.png">
<img width="1705" alt="error-img2" src="https://user-images.githubusercontent.com/12868906/113853449-3e59db00-97d0-11eb-8137-65ae046d2e83.png">

**Comment by b-zurg** [comment]
It seems that AbortController is not suppored by IE11: https://caniuse.com/abortcontroller

I recommend adding an abort controller poly fill to your project if you need to support IE11.  This seems promising: https://www.npmjs.com/package/abortcontroller-polyfill

I don't think I will change the source code of this repo in order to accommodate IE11.
